### ISSUE TITLE
Known memory leak

### ISSUE THREAD

**Issue by tylermumford** [tylermumford/localstatus#3]
Memory usage keeps increasing when using the tool in `--watch` mode. I've seen it climb up to 40 MB, which isn't terrible, but it's still a memory leak.

**Comment by tylermumford** [comment]
The memory leak has been greatly reduced. Previously, having localstatus running all weekend reached 40 MB. With the latest unreleased code, usage only reached a little over 10 MB. I'll close this issue after the next release.

**Comment by runeimp** [comment]
Was it an issue with caching file system events or some such?

**Comment by tylermumford** [comment]
My first implementation of `--watch` mode was overly simplistic. It started two goroutines, and one of them allocated a new input scanner every 3 minutes. The new code just initializes one scanner in the beginning. For a side-by-side, see [this change](https://github.com/tylermumford/localstatus/commit/640627b249d71adbf3a9bc3ada90df2d4083abb3#diff-ddacf1201170a1b8ae4a94352ca72159afa062e8c7237a6ba52276ca1c095f96).

Perhaps `--watch` isn't the most technically accurate name, since it doesn't actually watch the filesystem. It just runs again and again on a fixed interval.
